// Human view of the agents' shared work and memory. Mostly read-only: agents
// write it; the user observes and directs. All record text is rendered as text.
export async function mountKnowledge(root) {
  const css=document.createElement('link');css.rel='stylesheet';css.href='/account/knowledge/assets/knowledge.css';document.head.append(css);
  root.innerHTML=`<div class="kn-toolbar"><label>View <select id="kn-kind"><option value="deck">On deck</option><option value="knowledge">Knowledge (wiki)</option><option value="task">Tasks</option><option value="project">Projects</option><option value="concept">Concepts</option><option value="all">Everything</option></select></label><label>Band <select id="kn-band"></select></label><input id="kn-query" aria-label="Search" placeholder="Search pages, tasks and decisions…"><button id="kn-search">Search</button><button id="kn-new">New</button><button id="kn-refresh">Refresh</button></div><p id="kn-status" role="status"></p><div class="kn-layout"><section id="kn-list" aria-label="Records"></section><section id="kn-detail" aria-label="Page"><p>Select a page or task.</p></section></div><dialog id="kn-dialog"><form id="kn-form"><h2 id="kn-form-title"></h2><div id="kn-fields"></div><p id="kn-form-error" role="alert"></p><div class="kn-actions"><button type="button" id="kn-cancel">Cancel</button><button type="submit">Save</button></div></form></dialog>`;
  const $=s=>root.querySelector(s);let csrf='',bands=[],selected=null,timer=null,active=false,version=0;
  const el=(tag,txt,cls)=>{const e=document.createElement(tag);if(txt!==undefined&&txt!==null)e.textContent=txt;if(cls)e.className=cls;return e;};
  const date=t=>t?new Date(t*1000).toLocaleString():'';
  const ago=t=>{if(!t)return '';const m=Math.round((Date.now()/1000-t)/60);return m<1?'just now':m<60?m+'m ago':m<1440?Math.round(m/60)+'h ago':Math.round(m/1440)+'d ago';};
  async function api(action,body={}){const r=await fetch('/account/knowledge/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf,action,...body})});const d=await r.json();if(!r.ok||d.error||d.ok===false)throw Error(d.error||'Request failed');return d.result;}
  async function bootstrap(){const r=await fetch('/account/knowledge/api');if(!r.ok)throw Error('Sign in with your operator account to view Knowledge.');const d=await r.json();csrf=d.csrf;bands=d.bands;const keep=$('#kn-band').value;$('#kn-band').replaceChildren(...bands.map(b=>{const o=el('option',b.name);o.value=b.id;return o;}));if(bands.some(b=>b.id===keep))$('#kn-band').value=keep;else if(bands.some(b=>b.primary))$('#kn-band').value=bands.find(b=>b.primary).id;}
  const bandName=id=>(bands.find(b=>b.id===id)||{}).name||id;
  function button(label,fn,cls){const b=el('button',label,cls);b.onclick=()=>Promise.resolve().then(fn).catch(fail);return b;}
  // Body text with [[slug]] rendered as clickable page links; everything else stays plain text.
  function wiki(text,band){const pre=el('div',undefined,'kn-body');for(const part of (text||'').split(/(\[\[[a-z0-9][a-z0-9-]{0,79}\]\])/)){const m=part.match(/^\[\[(.+)\]\]$/);if(m){const a=button(m[1],()=>open(m[1],band),'kn-wikilink');pre.append(a);}else pre.append(document.createTextNode(part));}return pre;}
  function card(r,extra=[]){const b=button('',()=>open(r.id,r.band),'kn-card');b.append(el('small',r.kind+' · '+r.state+(r.verification&&r.kind==='knowledge'?' · '+r.verification:'')),el('strong',r.title));for(const x of extra)if(x)b.append(el('span',x));if(r.excerpt)b.append(el('span',r.excerpt.slice(0,160)));b.append(el('small',(r.slug?'[['+r.slug+']] · ':'')+ago(r.updated)));return b;}
  function field(name,label,value='',type='input'){const wrap=el('label',label);const e=document.createElement(type);e.name=name;e.value=value;wrap.append(e);$('#kn-fields').append(wrap);return e;}
  function showForm(title,build,submit){$('#kn-form-title').textContent=title;$('#kn-fields').replaceChildren();$('#kn-form-error').textContent='';build();$('#kn-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await submit(new FormData(e.target));$('#kn-dialog').close();await refresh();if(selected)await open(selected.id,selected.band);}catch(err){$('#kn-form-error').textContent=err.message;}finally{b.disabled=false;}};$('#kn-dialog').showModal();}
  function edit(record=null){showForm(record?'Edit '+record.kind:'New page, concept, project or task',()=>{
    const kind=field('kind','Type',record?.kind||'knowledge','select');for(const k of ['knowledge','concept','project','task']){const o=el('option',k);o.value=k;kind.append(o);}kind.value=record?.kind||'knowledge';kind.disabled=!!record;
    field('title','Title',record?.title||'');if(!record)field('slug','Slug (optional; lowercase-with-dashes)','');
    field('body','Body — link other pages with [[slug]]',record?.body||'','textarea');
    if(!record)field('parent','Parent (id or slug; project needs a concept, task needs a project or task)',selected&&selected.kind!=='knowledge'?selected.slug:'');
  },async f=>{if(record)await api('update',{id:record.id,band:record.band,request_id:crypto.randomUUID(),data:{revision:record.revision,patch:{title:f.get('title'),body:f.get('body')}}});else await api('create',{kind:f.get('kind'),band:$('#kn-band').value,request_id:crypto.randomUUID(),data:{title:f.get('title'),body:f.get('body'),...(f.get('slug')?{slug:f.get('slug')}:{}),...(f.get('parent')?{parent:f.get('parent')}:{})}});});}
  async function open(id,band){selected=await api('get',{id,...(band?{band}:{})});const r=selected;const box=$('#kn-detail');
    box.replaceChildren(el('small',r.kind+' · [['+r.slug+']] · '+bandName(r.band)+' · '+r.id),el('h2',r.title),el('p',r.state+(r.kind==='knowledge'?' · '+(r.attrs.verification||'unverified'):'')+' · revision '+r.revision+' · created by '+r.creator+' · updated '+ago(r.updated)));
    if(r.superseded_by)box.append(el('p','Superseded by ','kn-warn'),button('[['+r.superseded_by.slug+']] '+r.superseded_by.title,()=>open(r.superseded_by.id,r.band)));
    if(r.parent)box.append(button('↑ Parent',()=>open(r.parent,r.band)));
    box.append(wiki(r.body,r.band));
    for(const [key,label] of [['outcome','Outcome'],['blocked_reason','Blocked because']])if(r.attrs[key])box.append(el('h3',label),el('p',r.attrs[key]));
    for(const [key,label] of [['criteria','Acceptance criteria'],['workers','Workers'],['dependencies','Depends on'],['tags','Tags']]){const v=r.attrs[key]||[];if(v.length){box.append(el('h3',label));const ul=el('ul');for(const x of v)ul.append(el('li',x));box.append(ul);}}
    const actions=el('div',undefined,'kn-actions');actions.append(button('Edit text',()=>edit(r)));if(r.kind!=='knowledge')actions.append(button('New child',()=>edit()));if(r.state!=='archived')actions.append(button('Archive',async()=>{await api('update',{id:r.id,band:r.band,request_id:crypto.randomUUID(),data:{revision:r.revision,patch:{state:'archived'}}});await open(r.id,r.band);await refresh();}));box.append(actions);
    if(r.claims.length){box.append(el('h3','Claims'));for(const c of r.claims)box.append(el('p',c.actor+' · since '+date(c.started)+' · last active '+ago(c.last_active)+(c.released?' · released '+ago(c.released):'')+(c.dirty&&!c.released?' · needs hygiene':'')));}
    if(r.children.length){box.append(el('h3','Children'));for(const c of r.children)box.append(card({...c,band:r.band}));}
    if(r.backlinks.length){box.append(el('h3','What links here'));for(const b of r.backlinks)box.append(card({...b,band:r.band}));}
    if(r.links.length){box.append(el('h3','Audit trail'));const t=el('table',undefined,'kn-links');const h=el('tr');for(const c of ['When','Relation','Kind','Reference','By',''])h.append(el('th',c));t.append(h);for(const l of r.links.slice().reverse()){const tr=el('tr');tr.append(el('td',date(l.ts)),el('td',l.relation),el('td',l.kind),el('td',l.ref+(l.note?' — '+l.note:'')),el('td',l.actor),el('td',l.auto?'auto':''));t.append(tr);}box.append(t);}
    box.append(el('h3','History'));for(const e of r.events){const d=el('details');d.append(el('summary',date(e.ts)+' · '+e.action+' · '+e.actor),el('pre',JSON.stringify(e.data,null,2)));box.append(d);}
  }
  function renderDeck(deck){const list=$('#kn-list');list.replaceChildren();if(!deck.length){list.append(el('p','Nothing on deck yet. Agents create projects and tasks as they work.'));return;}
    for(const p of deck){const sec=el('section',undefined,'kn-deck');sec.append(button(p.project.title+' · '+bandName(p.band),()=>open(p.project.id,p.band),'kn-deck-title'));
      for(const [key,label] of [['in_progress','In progress'],['blocked','Blocked'],['paused','Paused'],['todo','To do'],['recently_done','Recently done']]){const items=p[key];if(!items.length)continue;sec.append(el('h4',label+' ('+items.length+')'));
        for(const t of items)sec.append(card({...t,band:p.band},[t.claimants&&t.claimants.length?'On it: '+t.claimants.map(c=>c.actor+' ('+ago(c.last_active)+')').join(', '):null,t.needs_hygiene?'Needs hygiene':null,t.blocked_reason?'Blocked: '+t.blocked_reason:null,t.latest_handoff?'Handoff '+ago(t.latest_handoff.ts):null,t.outcome?'Outcome: '+t.outcome:null]));}
      list.append(sec);}}
  async function refresh(){const v=++version;if(!csrf)await bootstrap();const query=$('#kn-query').value.trim(),kind=$('#kn-kind').value;$('#kn-band').disabled=kind==='deck'&&!query;
    if(kind==='deck'&&!query){const d=await api('deck');if(v!==version)return;$('#kn-status').textContent='What agents are working on across all bands.';renderDeck(d.deck);return;}
    let rows;if(query){const r=await api('search',{band:$('#kn-band').value,query,kind:['all','deck'].includes(kind)?null:kind});if(v!==version)return;rows=r.results.map(x=>({...x,excerpt:x.body,band:$('#kn-band').value}));$('#kn-status').textContent=r.semantic?'Semantic + keyword matches':'Keyword matches';}
    else{rows=(await api('list',{band:$('#kn-band').value,kind:kind==='all'?null:kind,data:{limit:200}})).records.map(x=>({...x,band:$('#kn-band').value}));if(v!==version)return;$('#kn-status').textContent='';}
    const list=$('#kn-list');list.replaceChildren();if(!rows.length)list.append(el('p',query?'No matches.':'Nothing here yet.'));for(const r of rows)list.append(card(r));}
  $('#kn-band').onchange=()=>refresh().catch(fail);$('#kn-kind').onchange=()=>refresh().catch(fail);$('#kn-search').onclick=()=>refresh().catch(fail);$('#kn-query').onkeydown=e=>{if(e.key==='Enter')refresh().catch(fail);};$('#kn-new').onclick=()=>edit();$('#kn-refresh').onclick=()=>refresh().catch(fail);$('#kn-cancel').onclick=()=>$('#kn-dialog').close();
  function fail(e){$('#kn-status').textContent=e.message;}
  return {activate(){active=true;refresh().catch(fail);timer=setInterval(()=>{if(active&&!document.hidden&&!$('#kn-dialog').open)refresh().catch(fail);},30000);},deactivate(){active=false;clearInterval(timer);}};
}
