// Human views over the same records agents use. All record text is rendered as text.
export async function mountKnowledge(root) {
  const css=document.createElement('link');css.rel='stylesheet';css.href='/account/knowledge/assets/knowledge.css';document.head.append(css);
  root.innerHTML=`<div class="kn-toolbar"><label>Band <select id="kn-band"></select></label><label>View <select id="kn-kind"><option value="attention">Needs attention</option><option value="concept">Concepts</option><option value="project">Projects</option><option value="task">Tasks</option><option value="knowledge">Knowledge</option><option value="all">Everything</option></select></label><input id="kn-worker" aria-label="Filter by worker name" placeholder="Worker name (optional)"><input id="kn-query" aria-label="Search knowledge and work" placeholder="Find related ideas, work, or decisions…"><button id="kn-search">Search</button><button id="kn-new">New record</button><button id="kn-refresh">Refresh</button></div><p id="kn-status" role="status"></p><div class="kn-layout"><section id="kn-list" aria-label="Records"></section><section id="kn-detail" aria-label="Record details"><p>Select a record to see scope, history, and who changed it.</p></section></div><dialog id="kn-dialog"><form id="kn-form"><h2 id="kn-form-title"></h2><div id="kn-fields"></div><p id="kn-form-error" role="alert"></p><div class="kn-actions"><button type="button" id="kn-cancel">Cancel</button><button type="submit">Save</button></div></form></dialog>`;
  const $=s=>root.querySelector(s);let csrf='',bands=[],selected=null,active=false,records=[],timer=null,refreshVersion=0;
  const el=(tag,txt,cls)=>{const e=document.createElement(tag);if(txt!==undefined)e.textContent=txt;if(cls)e.className=cls;return e;};
  const date=t=>new Date(t*1000).toLocaleString();
  async function api(action,body={}){const r=await fetch('/account/knowledge/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf,band:$('#kn-band').value,action,...body})});const d=await r.json();if(!r.ok||d.error||d.ok===false)throw Error(d.error||'Request failed');return d.result;}
  async function bootstrap(){const r=await fetch('/account/knowledge/api');if(!r.ok)throw Error('Sign in with your operator account to use Knowledge.');const d=await r.json();csrf=d.csrf;bands=d.bands;const value=$('#kn-band').value;$('#kn-band').replaceChildren(...bands.map(b=>{const o=el('option',b.name);o.value=b.id;return o;}));if(bands.some(b=>b.id===value))$('#kn-band').value=value;else if(bands.some(b=>b.primary))$('#kn-band').value=bands.find(b=>b.primary).id;}
  function field(name,label,value='',type='input'){const wrap=el('label',label);const e=document.createElement(type);e.name=name;e.value=value;wrap.append(e);$('#kn-fields').append(wrap);return e;}
  function listField(name,label,values=[]){return field(name,label,values.join('\n'),'textarea');}
  const lines=v=>v.split('\n').map(s=>s.trim()).filter(Boolean);
  function showForm(title,build,submit){$('#kn-form-title').textContent=title;$('#kn-fields').replaceChildren();$('#kn-form-error').textContent='';build();$('#kn-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{await submit(new FormData(e.target));$('#kn-dialog').close();await refresh();if(selected)await open(selected.id);}catch(e){$('#kn-form-error').textContent=e.message;}finally{button.disabled=false;}};$('#kn-dialog').showModal();}
  function edit(record=null){showForm(record?'Edit '+record.kind:'New concept, project, task, or knowledge',()=>{
    const kind=field('kind','Type',record?.kind||'concept','select');for(const k of ['concept','project','task','knowledge']){const o=el('option',k);o.value=k;kind.append(o);}kind.value=record?.kind||'concept';kind.disabled=!!record;
    field('title','Title',record?.title||'');field('body','Outcome, scope, or knowledge',record?.body||'','textarea');
    if(!record){const parent=field('parent','Parent concept / project / task','','select');parent.append(el('option','No parent'));parent.options[0].value='';for(const r of [...records,...(selected&&!records.some(r=>r.id===selected.id)?[selected]:[])].filter(r=>r.kind!=='knowledge')){const o=el('option',r.kind+': '+r.title);o.value=r.id;parent.append(o);}if(selected&&selected.kind!=='knowledge')parent.value=selected.id;}
    for(const [key,label] of [['criteria','Acceptance criteria (one per line)'],['workers','Affected worker names (one per line)'],['sources','Sources / provenance (one per line)'],['evidence','Verification evidence (one per line)'],['dependencies','Dependency task IDs'],['related','Related record IDs'],...(!record?[['supersedes','Superseded knowledge IDs']]:[])])listField(key,label,record?.attrs[key]||[]);
    if(record?.kind==='knowledge'||!record){const v=field('verification','Verification',record?.attrs.verification||'unverified','select');for(const x of ['unverified','observed','verified','disputed']){const o=el('option',x);o.value=x;v.append(o);}v.value=record?.attrs.verification||'unverified';}
  },async f=>{const attrs={};for(const k of ['criteria','workers','sources','evidence','dependencies','related'])attrs[k]=lines(f.get(k)||'');if(!record)attrs.supersedes=lines(f.get('supersedes')||'');if(f.get('verification'))attrs.verification=f.get('verification');const content={title:f.get('title'),body:f.get('body'),attrs};if(record)await api('update',{id:record.id,request_id:crypto.randomUUID(),data:{revision:record.revision,patch:content}});else await api('create',{kind:f.get('kind'),request_id:crypto.randomUUID(),data:{...content,parent:f.get('parent')||null}});});}
  function button(label,fn){const b=el('button',label);b.onclick=()=>Promise.resolve().then(fn).catch(e=>{$('#kn-status').textContent=e.message;});return b;}
  async function open(id){selected=await api('get',{id});const r=selected;const box=$('#kn-detail');box.replaceChildren(el('small',r.kind+' · '+r.id),el('h2',r.title),el('p',r.state+' · revision '+r.revision+' · '+date(r.updated)),el('pre',r.body,'kn-body'));
    if(r.parent)box.append(button('↑ Open parent',()=>open(r.parent)));
    const actions=el('div',undefined,'kn-actions');actions.append(button('Edit',()=>edit(r)),button('New child',()=>edit()));
    for(const state of (r.kind==='task'?['proposed','ready','blocked','completed','cancelled','archived']:['proposed','completed','archived']))actions.append(button(state==='proposed'?'Reopen':state,async()=>{await api('update',{id:r.id,request_id:crypto.randomUUID(),data:{revision:r.revision,patch:{state}}});await open(r.id);await refresh();}));box.append(actions);
    for(const [key,label] of [['criteria','Acceptance criteria'],['workers','Affected workers'],['dependencies','Dependencies'],['sources','Sources'],['evidence','Evidence'],['related','Related records'],['supersedes','Supersedes']]){const vals=r.attrs[key]||[];if(vals.length){box.append(el('h3',label));const ul=el('ul');for(const val of vals){const li=el('li');if(['related','dependencies','supersedes'].includes(key))li.append(button(val,()=>open(val)));else li.textContent=val;ul.append(li);}box.append(ul);}}
    box.append(el('p','Verification: '+(r.attrs.verification||'unverified')));
    if(r.children.length){box.append(el('h3','Children'));for(const c of r.children)box.append(button(c.state+' · '+c.title,()=>open(c.id)));}
    box.append(el('h3','History'));for(const e of r.events){const d=el('details');d.append(el('summary',date(e.ts)+' · '+e.action+' · '+e.actor),el('pre',JSON.stringify(e.data,null,2)));box.append(d);}
  }
  async function refresh(){const version=++refreshVersion;if(!csrf)await bootstrap();const query=$('#kn-query').value.trim(),kind=$('#kn-kind').value;let result,loaded;
    if(query){result=await api('search',{query,kind:['all','attention'].includes(kind)?null:kind,data:{worker:$('#kn-worker').value.trim()||null}});if(version!==refreshVersion)return;loaded=result.results;$('#kn-status').textContent=result.semantic?'Semantic + keyword matches':'Keyword matches · semantic service unavailable or warming up';}
    else {loaded=(await api('list',{kind:['all','attention'].includes(kind)?null:kind,data:{limit:200,attention:kind==='attention',worker:$('#kn-worker').value.trim()||null}})).records;}
    if(version!==refreshVersion)return;records=loaded;
    const show=kind==='attention'?records.filter(r=>r.state==='proposed'||['blocked','interrupted'].includes(r.state)):records;
    const list=$('#kn-list');list.replaceChildren();if(!show.length)list.append(el('p',query?'No matching records.':'Nothing here yet. Create a concept to begin.'));
    for(const r of show){const b=button('',()=>open(r.id));b.className='kn-card';b.append(el('small',r.kind+' · '+r.state),el('strong',r.title),el('span',r.body.slice(0,160)),el('small',date(r.updated)));list.append(b);}
  }
  $('#kn-band').onchange=()=>{selected=null;$('#kn-detail').replaceChildren(el('p','Select a record.'));refresh().catch(fail);};$('#kn-worker').onchange=()=>refresh().catch(fail);$('#kn-kind').onchange=()=>refresh().catch(fail);$('#kn-search').onclick=()=>refresh().catch(fail);$('#kn-query').onkeydown=e=>{if(e.key==='Enter')refresh().catch(fail);};$('#kn-new').onclick=async()=>{try{records=(await api('list',{data:{limit:200}})).records;edit();}catch(e){fail(e);}};$('#kn-refresh').onclick=()=>refresh().catch(fail);$('#kn-cancel').onclick=()=>$('#kn-dialog').close();
  function fail(e){$('#kn-status').textContent=e.message;}
  return {activate(){active=true;refresh().catch(fail);timer=setInterval(()=>{if(active&&!document.hidden&&!$('#kn-dialog').open)refresh().catch(fail);},30000);},deactivate(){active=false;clearInterval(timer);}};
}
