#!/usr/bin/env python3
"""Regenerate docs/operations/settings-reference.md from the settings schema
(rook/hub/settings_schema.py plus every plugin's ``SETTINGS``), so the list of
settings, their environment variables and defaults cannot drift from the code
(docs/design/settings.md, P11).

    python tools/gen_settings_reference.py          # rewrite the file
    python tools/gen_settings_reference.py --check  # exit 1 if it is stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "docs" / "operations" / "settings-reference.md"
sys.path.insert(0, str(ROOT))

HEADER = """# Settings reference

Generated by `tools/gen_settings_reference.py` from the settings schema; do not
edit by hand. The dashboard's **Settings** page shows the same keys with their
current value and source. How the sources combine, highest first:

1. an environment variable or command-line flag (locks the key in the UI);
2. a value stored on the Settings page (user, then worker, band, hub scope);
3. the legacy `setup.json` (first-run wizard), until a value is stored;
4. the built-in default.

The band key is the exception: it lives in the enrollment database (rotate it
on the Bands page) and `ROOK_BAND_PSK` only seeds the first band.

Columns: **Scope** is the key's home scope (`+worker`, `+user`: may be
overridden there). **Apply**: `live` (next read), `reload` (plugin reload),
`restart` (process restart), `risky` (commit-confirmed worker restart).
**Bootstrap** keys are read before the settings store is reachable, so they
are set only in the environment or on the command line.
"""


def _fmt(v) -> str:
    if v is None or v == "" or v == [] or v == {}:
        return ""
    if isinstance(v, bool):
        return "on" if v else "off"
    s = str(v)
    return ("`" + s.replace("|", "\\|") + "`") if len(s) < 48 else "`" + s[:44] + "…`"


def render() -> str:
    from rook.hub.settings_schema import PLUGIN_TITLES, Schema
    schema = Schema()
    sections: dict[str, list] = {}
    for e in schema:
        if e.origin == "core":
            title = "Core: " + (e.setting.group or "General")
        else:
            title = PLUGIN_TITLES.get(e.namespace, (e.plugin or e.namespace).capitalize())
            title = f"{title} ({e.origin.replace('-', ' ')}, runs in {e.owner})"
        sections.setdefault(title, []).append(e)
    out = [HEADER]
    order = sorted(sections, key=lambda t: (not t.startswith("Core"), t.lower()))
    for title in order:
        out.append(f"\n## {title}\n")
        out.append("| Key | Label | Scope | Type | Default | Env / flag | Apply |")
        out.append("|---|---|---|---|---|---|---|")
        for e in sections[title]:
            s = e.setting
            scope = s.scope + "".join("+" + o for o in s.overridable)
            env = ", ".join(f"`{n}`" for n in e.env_names())
            if s.flag:
                env = (env + ", " if env else "") + f"`{s.flag}`"
            apply = s.apply + (" · bootstrap" if s.bootstrap else "")
            if e.managed:
                apply += f" · managed in {e.managed}"
            label = (s.label or s.name) + (" (secret)" if s.secret else "")
            if s.deprecated:
                label += f" — deprecated: {s.deprecated}"
            default = "" if s.secret else _fmt(s.default)
            out.append(f"| `{e.key}` | {label.replace('|', '/')} | {scope} | {s.type} | "
                       f"{default} | {env} | {apply} |")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
    if args.check:
        if current != text:
            print(f"{TARGET.relative_to(ROOT)} is stale: run python tools/gen_settings_reference.py")
            return 1
        return 0
    if current != text:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(text, encoding="utf-8")
        print(f"updated {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
