[env:t-dongle-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_speed = 921600
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCONFIG_ASYNC_TCP_RUNNING_CORE=1
    -DASYNCWEBSERVER_REGEX=1

lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.0
    adafruit/Adafruit GFX Library@^1.11.0
    mathieucarbou/ESPAsyncWebServer@^3.6.0
